### PR TITLE
improve helper security and install location

### LINKED ISSUE #11: 能否更改 helper 的安装方式
目前会创建`~/.iconchanger/`，脚本权限 0777 ，`/etc/sudoer` 任何人都可以无密码执行 `sudo helper.sh`
1. 我的家目录已经很拥挤了
2. 任何用户都可以更改 helper 脚本并无密码 `sudo` 执行，这真的很危险

### LINKED ISSUE #24: macOS 12.6.2 打开一直请求完全磁盘访问
应用程序已拖入应用文件夹，已经手动 Add 完全磁盘权限，重启后依旧显示 check 页面。

Intel 平台, iMac 27‘’ 5K 2015 Late.

### PR DESCRIPTION
**Pull request by ghostflyby**
# 安全相关
## helper
1. 更改 helper 安装位置为 `/Library/Application Support/IconChanger`
2. 将安装脚本嵌入可执行二进制
3. 更改对应的构建流程
4. 移除无用的 shell 脚本资源
5. 降低 helper 脚本权限
6. sudoer 配置改为单独的 `/etc/sudoer.d/iconchanger` 文件
7. sudoer 配置检验 helper 摘要
8. 更改安装脚本使其移除旧的 `~/.iconchanger` 文件和 sudoer 规则

closes #11 

## 完全磁盘访问权限
移除了权限请求，因为更改图标使用 sudo，而 LaunchPad 数据库似乎是默认 owner 可写的，如果有错误再修改

closes #24 

# 杂项
移除了一个 swift playground

### CODE REVIEW

**Comment by underthestars-zhy** [comment]
I will look on it. But I am currently changing the shell file to the privilege helper, so it can be more safer.

**Comment by ghostflyby** [comment]
I shall rebase my commits or just close the PR on demand then
________________________________
发件人: Ryan Zhu ***@***.***>
发送时间: Saturday, March 18, 2023 9:02:41 PM
收件人: underthestars-zhy/IconChanger ***@***.***>
抄送: ghostflyby ***@***.***>; Author ***@***.***>
主题: Re: [underthestars-zhy/IconChanger] improve helper security and install location (PR #33)


I will look on it. But I am currently changing the shell file to the privilege helper, so it can be more safer.

―

**Comment by underthestars-zhy** [comment]
I thought some part maybe still helpful. Like remove the full disk permission.

**Comment by ghostflyby** [comment]
replaced by #34

**Pull request closed without merging**
